require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

inherit_mode:
  merge:
    - Include
    - Exclude

Naming/FileName:
  Exclude:
    - '**/r18n-rails.rb'

Style/AsciiComments:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line
Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'

Style/NumericLiterals:
  Exclude:
    - '**/db/**/*'

Rails/RakeEnvironment:
  Enabled: false

## https://github.com/rubocop/rubocop-rails/issues/484
Rails/EnvironmentVariableAccess:
  AllowReads: true

RSpec/NestedGroups:
  Enabled: false

# TODO: fix offenses and enable cops

Metrics/AbcSize:
  Exclude:
    - 'lib/r18n-rails/hooks_helper.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/r18n-rails/hooks_helper.rb'

Style/Documentation:
  Exclude:
    - 'lib/r18n-rails/hooks_helper.rb'
