require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  # - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

inherit_mode:
  merge:
    - Include
    - Exclude

Naming/FileName:
  Exclude:
    - '**/r18n-rails.rb'

Style/AsciiComments:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'

Style/NumericLiterals:
  Exclude:
    - '**/db/**/*'

Rails/RakeEnvironment:
  Enabled: false


# TODO: fix offenses and enable cops

Metrics/AbcSize:
  Exclude:
    - 'lib/r18n-rails/hooks_helper.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/r18n-rails/hooks_helper.rb'

Style/Documentation:
  Exclude:
    - 'lib/r18n-rails/hooks_helper.rb'
